#!/usr/bin/env sh

# remove existing
rm .gitconfig
rm .gitignore_global
rm -rf .clojure
rm -rf .config

# add them again
# git
ln /Users/filipesilva/.gitconfig .gitconfig
ln /Users/filipesilva/.gitignore_global .gitignore_global
# clojure
mkdir .clojure
ln /Users/filipesilva/.clojure/deps.edn .clojure/deps.edn
# doomemacs
mkdir -p .config/doom
ln /Users/filipesilva/.config/doom/cheatsheet.md .config/doom/cheatsheet.md
ln /Users/filipesilva/.config/doom/evil-cleverparens-readme.md .config/doom/evil-cleverparens-readme.md
ln /Users/filipesilva/.config/doom/packages.el .config/doom/packages.el
ln /Users/filipesilva/.config/doom/config.el .config/doom/config.el
ln /Users/filipesilva/.config/doom/init.el .config/doom/init.el
